administrador/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ADMIN-DJANGO
    path('admin/', admin.site.urls),

    # APLICACION USUARIO
    path('', include('gestion_usuarios.urls')),

    # APLICACION REPOSITORIO DE TITULADOS
    path('', include('repositoriotitulados.urls')),
    
    # APLICACION SEG_MOD_GRADUACION
    path('', include('seg_mod_graduacion.urls')),
    
    # APLICACIION INTERACCION SOCIAL
    path('', include('interccion_social.urls')),
    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seg_mod_graduacion/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler403
from .views import handle_permission_denied
from seg_mod_graduacion import views
from .views import ModalidadCreateView, ModalidadListView, ModalidadUpdateView

urlpatterns = [    
    #segguimiento modalidad de graduacion investigacion cientifica
    path('invcientifica/agregar_investigacion/', views.agregar_investigacion, name='agregar_investigacion'),
    path('invcientifica/vista_investigacion/',views.vista_investigacion, name='vista_investigacion'),
    path('invcientifica/ProyectosParaAprobar/', views.ProyectosParaAprobar.as_view(), name='ProyectosParaAprobar'),
    path('AprobarProyecto/<int:proyecto_id>/', views.AprobarProyecto.as_view(), name='AprobarProyecto'),
    path('RechazarProyecto/<int:proyecto_id>/', views.RechazarProyecto.as_view(), name='RechazarProyecto'),
    path('invcientifica/global_settings/', views.global_settings_view, name='global_settings'),
    
    #seguimiento modalidad de graduacion perfil de proyecto
    path('perfil/agregar_perfil/', views.agregar_perfil, name='agregar_perfil'),
    path('perfil/vista_perfil/',views.vista_perfil, name='vista_perfil'),
    path('perfil/PerfilesParaAprobar/', views.PerfilesParaAprobar.as_view(), name='PerfilesParaAprobar'),
    path('AprobarPerfil/<int:proyecto_id>/', views.AprobarPerfil.as_view(), name='AprobarPerfil'),
    path('RechazarPerfil/<int:proyecto_id>/', views.RechazarPerfil.as_view(), name='RechazarPerfil'),

    #seguimiento modalidad de graduacion proyecto final
    path('controlador/actividad_control/nueva/', views.crear_actividad_control, name='crear_actividad_control'),
    path('controlador/editar_actividad_control/<int:pk>/editar/', views.editar_actividad_control, name='editar_actividad_control'),
    path('controlador/lista_actividad_control/', views.lista_actividad_control, name='lista_actividad_control'),
    
    path('proyectofinal/revision/<int:actividad_id>/', views.revisar_actividad, name='revisar_actividad'),
    path('controlador/revision/<int:actividad_id>/', views.revision, name='revision'),
    
    path('controlador/listaractividades/', views.listaractividades, name='listaractividades'),
    path('controlador/listaactividades/', views.listaactividades, name='listaactividades'),
    
    path('proyectofinal/crear_actividad/nueva/', views.crear_actividad, name='crear_actividad'),
    path('proyectofinal/actividad/', views.lista_actividad, name='lista_actividad'),
    
    path('modalidad/modalidadagregar/', ModalidadCreateView.as_view(), name='modalidadagregar'),
    path('modalidades/', ModalidadListView.as_view(), name='listarmodalidades'),
    path('modalidad/editarmodalidad/<int:pk>/', ModalidadUpdateView.as_view(), name='editarmodalidad'),
]
handler403 = handle_permission_denied

seg_mod_graduacion/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from datetime import date
from django.conf import settings
from django.core.exceptions import ValidationError  

User = get_user_model()

ESTADO_CHOICES = [
    ('Aprobado', 'Aprobado'),
    ('Pendiente', 'Pendiente'),
    ('Rechazado', 'Rechazado'),
]


#class TutorExterno(models.Model):
#    nombre = models.CharField(max_length=100)
#   apellido = models.CharField(max_length=100)
#
#    def __str__(self):
#        return f"{self.nombre} {self.apellido}"

#class Materia(models.Model):
#    sigla = models.CharField(max_length=10)
#    nombre = models.CharField(max_length=100)
#    plan = models.CharField(max_length=100)
#
#    def __str__(self):
#        return f"{self.nombre} ({self.sigla})"

class Modalidad(models.Model):
    nombre = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.nombre

class InvCientifica(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado')
    invtitulo = models.CharField(max_length=450, verbose_name='Agregar Titulo')
    slug = models.SlugField(unique=True)
    invfecha_creacion = models.DateTimeField(auto_now_add=True)
    invdescripcion = models.TextField(verbose_name='Agregar una Descripcion Breve', blank=True)
    invdocumentacion = models.FileField(upload_to='documento/proyecto', verbose_name='Agregar Documentacion', null=True, blank=True)
    investado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')

    def __str__(self):
        return self.invtitulo

class ComentarioInvCientifica(models.Model):
    invcomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    invfecha_post = models.DateTimeField(auto_now_add=True)
    invproyecto_relacionado = models.ForeignKey(InvCientifica, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-invfecha_post']

    def __str__(self):
        return self.invcomentario[:15] + '...' if len(self.invcomentario) > 15 else self.invcomentario

class InvSettings(models.Model):
    habilitarInv = models.BooleanField(default=True, verbose_name='Habilitar Formulario')

    def __str__(self):
        return "Configuración Global"

class PerfilProyecto(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado')
    pertitulo = models.CharField(max_length=450, verbose_name='Agregar Titulo Perfil')
    slug = models.SlugField(unique=True)
    perfecha_creacion = models.DateTimeField(auto_now_add=True)
    perdescripcion = models.TextField(verbose_name='Agregar una Descripcion', blank=True)
    perdocumentacion = models.FileField(upload_to='documento/proyecto', verbose_name='Agregar Documentacion', null=True, blank=True)
    permodalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE, verbose_name='Seleccione Una Modalidad')
    perestado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')

    def __str__(self):
        return self.pertitulo

class ComentarioPerfil(models.Model):
    percomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    perfecha_post = models.DateTimeField(auto_now_add=True)
    perproyecto_relacionado = models.ForeignKey(PerfilProyecto, on_delete=models.CASCADE, related_name='comentarios')

    class Meta:
        ordering = ['-perfecha_post']

    def __str__(self):
        return self.percomentario[:15] + '...' if len(self.percomentario) > 15 else self.percomentario
    
####################################

class ActividadControl(models.Model):
    estudiante = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_estudiante', on_delete=models.CASCADE)
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_tutor', on_delete=models.CASCADE)
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_jurado_1', on_delete=models.CASCADE)
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_jurado_2', on_delete=models.CASCADE)
    jurado_3 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_jurado_3', on_delete=models.CASCADE)
    modalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE,  verbose_name='Seleccione Una Modalidad')

    def habilitar_actividad(self):
        actividad, created = Actividad.objects.get_or_create(
            estudiante=self.estudiante,
            defaults={
                'tutor': self.tutor,
                'jurado_1': self.jurado_1,
                'jurado_2': self.jurado_2,
                'jurado_3': self.jurado_3,
                'modalidad': self.modalidad,
                'habilitada': True
            }
        )
        if not created:
            actividad.tutor = self.tutor
            actividad.jurado_1 = self.jurado_1
            actividad.jurado_2 = self.jurado_2
            actividad.jurado_3 = self.jurado_3
            actividad.modalidad = self.modalidad
            actividad.habilitada = True
            actividad.save()
        return actividad

    def __str__(self):
        return f"ActividadControl for {self.estudiante}"
    
class Actividad(models.Model):
    estudiante = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividades_estudiante', on_delete=models.CASCADE)
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividades_tutor', on_delete=models.CASCADE)
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividades_jurado_1', on_delete=models.CASCADE)
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividades_jurado_2', on_delete=models.CASCADE)
    jurado_3 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividades_jurado_3', on_delete=models.CASCADE)
    modalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE)
    habilitada = models.BooleanField(default=False)
    titulo = models.CharField(max_length=450)
    resumen = models.TextField(max_length=500)
    fecha = models.DateField(default=timezone.now)
    guia_externo = models.CharField(max_length=250, default='Ninguno')
    documentacion = models.FileField(upload_to='documento/proyecto', verbose_name='Agregar Documentacion', null=True, blank=True)
    estado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')
    jurado_1_aprobado = models.BooleanField(default=False)
    jurado_2_aprobado = models.BooleanField(default=False)
    jurado_3_aprobado = models.BooleanField(default=False)

    def __str__(self):
        return f"Actividad for {self.estudiante}"
    
    @property
    def latest_comments(self):
        return self.comentarios.order_by('-actfecha_post')[:7]
    
    def save(self, *args, **kwargs):
        if self.estado in ['Aprobada', 'Rechazada']:
            # Verificar que todos los jurados han aprobado
            if not (self.jurado_1_aprobado and self.jurado_2_aprobado and self.jurado_3_aprobado):
                raise ValidationError("No se puede cambiar el estado sin la aprobación de todos los jurados.")
        
        super().save(*args, **kwargs)
    
    def transferir_a_repositorio(self, periodo, anio_ingreso, anio_egreso, numero_acta, nota_aprobacion):
        repo_actividad, created = ActividadRepositorio.objects.get_or_create(
            estudiante=self.estudiante,
            tutor=self.tutor,
            jurado_1=self.jurado_1,
            jurado_2=self.jurado_2,
            jurado_3=self.jurado_3,
            titulo=self.titulo,
            resumen=self.resumen,
            modalidad=self.modalidad,
            fecha=self.fecha,
            guia_externo=self.guia_externo,
            documentacion=self.documentacion,
            estado=self.estado,
            jurado_1_aprobado=self.jurado_1_aprobado,
            jurado_2_aprobado=self.jurado_2_aprobado,
            jurado_3_aprobado=self.jurado_3_aprobado,
            periodo=periodo,
            anio_ingreso=anio_ingreso,
            anio_egreso=anio_egreso,
            numero_acta=numero_acta,
            nota_aprobacion=nota_aprobacion
        )
        return repo_actividad
    
class Comentarioactividad(models.Model):
    actcomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    actfecha_post = models.DateTimeField(auto_now_add=True)
    actproyecto_relacionado = models.ForeignKey(Actividad, on_delete=models.CASCADE, related_name='comentarios')

    class Meta:
        ordering = ['-actfecha_post']

    def __str__(self):
        return self.actcomentario[:15] + '...' if len(self.actcomentario) > 15 else self.actcomentario
 
 
 
###  repositorio titulados  ###
   
class ActividadRepositorio(models.Model):
    estudiante = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='repo_estudiante', on_delete=models.CASCADE)
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='repo_tutor', on_delete=models.CASCADE)
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='repo_jurado_1', on_delete=models.CASCADE)
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='repo_jurado_2', on_delete=models.CASCADE)
    jurado_3 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='repo_jurado_3', on_delete=models.CASCADE)
    habilitada = models.BooleanField(default=False)
    titulo = models.CharField(max_length=450 )
    resumen = models.TextField(max_length=500 )

seg_mod_graduacion/templates/invcientifica/ProyectosParaAprobar.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<article class="container "> 
    <h1 class="text-center fontI titlesuperior">AREA DE REVISION DE FORMULARIOS INVESTIGACÓN CIENTIFICA </h1>
    <br>
    {% if proyectos.items %}
        {% for proyecto, formulario in proyectos.items %}
        <div class="container">
            <div class="mb-2 mx-auto contrevision" style="max-width: 840px;">
                <div class="row g-0 ">
                    <div class="col-md-4  m-2">
                        {% if proyecto.user.imagen %}
                            <img src="{{ proyecto.user.imagen.url }}" class="p-2 mt-4  no-gutters img-fluid rounded-left and rounded-right to rounded-start and rounded-end" style="height: 300px;" alt="...">
                        {% else %}
                            <img src="{% static 'img/SINFOTO.webp' %}" class="p-2 mt-4  no-gutters img-fluid rounded-left and rounded-right to rounded-start and rounded-end" style="height: 300px;" alt="...">
                        {% endif %}
                    </div>
                    <div class="col-md-7 px-2">
                        <div class="card-body"><br>
                            <h5 class="title pb-1 fontI colortitle">Titulo : {{ proyecto.invtitulo }}</h5>
                            <h5 class="fontI colorestados">Postulante: {{ proyecto.user.nombre }} {{ proyecto.user.apellido }}</h5>
                            <p class="fontI px-1 colortext">Descripcion:<br>{{ proyecto.invdescripcion }}</p>
                            <h2 class="contdoc col-lg-7 col-7 " data-label="Documento Proyecto"><a href="{{ proyecto.invdocumentacion.url }}" class="list-group-item list-group-item-action">
                                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-files" viewBox="0 0 16 16">
                                    <path d="M13 0H6a2 2 0 0 0-2 2 2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h7a2 2 0 0 0 2-2 2 2 0 0 0 2-2V2a2 2 0 0 0-2-2m0 13V4a2 2 0 0 0-2-2H5a1 1 0 0 1 1-1h7a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1M3 4a1 1 0 0 1 1-1h7a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"/>
                                </svg> Ver Documento Evaluar</a></h2>
                        </div>
                    </div>
                </div>
                <br>
                <p class="px-3 fontI colortext comentario">Comentario Dirigio para el Proyecto</p>
                <div class="container fontI px-2">
                    <form id="approvalForm" method="POST" action="{% url 'ProyectosParaAprobar' %}">
                        {% csrf_token %}
                        <input type="hidden" name="proyecto_id" value="{{ proyecto.id }}">
                        <textarea class="comentari-field  contdoc" name="comentario_texto" required></textarea>
                        <br><br>
                        <button type="button" name="aprobar" class="btn btn-success fontII me-2 " data-bs-toggle="modal" data-bs-target="#approveModal">Aprobar</button> 
                        <button type="button" name="rechazar" class="btn btn-danger fontII " data-bs-toggle="modal" data-bs-target="#rejectModal">Rechazar</button>
                    </form>
                    <br>
                </div><br>
        {% endfor %}
    {% else %}
        <p class="text-center fontI colorestados">Lista Formularios Investigación para Aprobar Vacía</p>
    {% endif %}
</article> 
<br>
<!-- Modal de confirmación de aprobación -->
<div class="modal fade" id="approveModal" tabindex="-1" aria-labelledby="approveModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content bg-mdal">
        <div class="modal-header">
          <h5 class="modal-title font" id="approveModalLabel">Confirmar Aprobación</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body text-center font">
            <img src="{% static 'img/siguiente.png' %}" class="img-close" alt="" /><br>
            ¿Estás seguro que quiere Aprobar formulario?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary fontII" data-bs-dismiss="modal">Cerrar</button>
          <button type="button" class="btn btn-success fontII" onclick="submitForm('aprobar')">Sí, Aprobar</button>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Modal de confirmación de rechazo -->
  <div class="modal fade" id="rejectModal" tabindex="-1" aria-labelledby="rejectModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content bg-mdal">
        <div class="modal-header">
          <h5 class="modal-title font" id="rejectModalLabel">Confirmar Rechazo</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body text-center font">
            <img src="{% static 'img/rechazado.png' %}" class="img-close" alt="" /><br>
            ¿Estás seguro que quiere Rechazar formulario?
        </div>
        <div class="modal-footer ">
          <button type="button" class="btn btn-secondary fontII " data-bs-dismiss="modal">Cerrar</button>
          <button type="button" class="btn btn-danger  fontII" onclick="submitForm('rechazar')">Sí, Rechazar</button>
        </div>
      </div>
    </div>
</div>
<script>
    function submitForm(action) {
      const form = document.getElementById('approvalForm');
      const hiddenInput = document.createElement('input');
      hiddenInput.type = 'hidden';
      hiddenInput.name = action;
      form.appendChild(hiddenInput);
      form.submit();
    }
</script>
{% endblock %}

seg_mod_graduacion/templates/invcientifica/agregar_investigacion.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}
{% block title %}Crear Form{% endblock %}
{% load static %}
{% block content %}

<div class="container px-lg-5 font pb-5">
  <div class="no-gutters container px-lg-5 px-2">
    <h1 class="text-center pb-4 pt-4  titlesuperior">AGREGAR NUEVO FORMULARIO ALCANZE DE PROYECTO</h1>
    {% if form_disabled %}
      <p class="text-end text colorestados ">El formulario de investigación está deshabilitado para el Usuario.</p>
    {% endif %}
    <article class="pb-5 colortext" >
      <form id="pot" method="post" enctype="multipart/form-data" onsubmit="showConfirmationModal(event)">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <input name="" id="" class="btn btn-success me-2 fontII" type="submit" value="Enviar Informacion" {% if form_disabled %}disabled{% endif %}>
        <a class="btn btn-danger fontII" href="{% url 'dashboard' %}">Cancelar</a>
      </form>
      <br>
    </article>
  </div> 
</div>


<!-- Modal de confirmación -->
<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content bg-mdal">
      <div class="modal-header">
        <h5 class="modal-title font" id="confirmationModalLabel"> Confirmacion de Formulario</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center font">
        <img src="{% static 'img/confi.png' %}" class="img-close" alt="" /><br>
        ¡Formulario Enviado con Exito!
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

<script>
  function showConfirmationModal(event) {
    event.preventDefault(); 
    $('#confirmationModal').modal('show'); 
    
    setTimeout(function() {
      $('#confirmationModal').modal('hide'); 
      document.getElementById("pot").submit(); 
    }, 2000);
  }
</script>
{% endblock %}

seg_mod_graduacion/templates/invcientifica/global_settings.html
{% extends 'dashboard.html'%} {% load static %} {% load crispy_forms_tags %}{% block content %}
<h1 class="text-center font">HABILITACIÓN DE FECHAS PARA PROYECTO INTERACION SOCIAL</h1>
<div class="container mt-3 pt-3">
  <div class="row pb-5 ">
    <div class="col-md-8  offset-md-2 pb-5">
      <div class="card contdoc">
        <div class="card-body font text-center">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary fontII" type="submit">Guardar</button>
                <a class="btn btn-danger fontII" href="{% url 'dashboard' %}">Camcelar</a>
            </form>
        </div>
        <br />
      </div>
    </div>
  </div>
</div>
{% endblock %}

seg_mod_graduacion/templates/invcientifica/vista_investigacion.html
{% extends 'dashboard.html' %}
{% load static %}
{% block content %}

<h1 class="text-center py-2 titlesuperior">VISTA Y ESTADO DE FORMULARIO INVESTIGACION CIENTIFICA</h1>
{% if proyectos %}
<div class="container mt-lg-2 mt-5">
  {% for proyecto in proyectos %}
  <div class="card narrow-card">
    <div class="row no-gutters">
      <!-- Foto en un lado -->
      {% if proyecto.user.imagen %}
        <div class="col-md-3 col-lg-3 centered-img">
            <img src="{{ proyecto.user.imagen.url }}" class="card-img imgperfil p-2" alt="{{ proyecto.user.username }}" />
        </div>
      {% else %}
        <div class="col-md-3 col-lg-3 centered-img">
            <img src="{% static 'img/SINFOTO.webp' %}" class="card-img imgperfil" alt="" />
        </div>
      {% endif %}
      
      <!-- Contenido en el otro lado -->
      <div class="col-md-7 col-lg-8 pb-5">
        <div class="card-body">
          <!-- Texto con formato pre -->
          <pre class="fecha fontI colorestados">                                                                                                 Enviado el : {{ proyecto.invfecha_creacion }}</pre>
          <!-- Título -->
          <h5 class="title pb-1 text-center fontI colortitle ">{{ proyecto.invtitulo }}</h5>
          <!-- Descripción -->
          <p class="fontI colortext">Descripción:<br>{{ proyecto.invdescripcion }}</p>
          <div class="container text-center">
            <div class="row">
              <div class="col-4 contdoc">
                <div class="d-flex align-items-center">
                  <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-file-earmark-richtext-fill" viewBox="0 0 16 16">
                    <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0M9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1M7 6.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0m-.861 1.542 1.33.886 1.854-1.855a.25.25 0 0 1 .289-.047l1.888.974V9.5a.5.5 0 0 1-.5.5H5a.5.5 0 0 1-.5-.5V9s1.54-1.274 1.639-1.208M5 11h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1m0 2h3a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1"/>
                  </svg>
                  <a href="{{ proyecto.invdocumentacion.url }}" class="list-group-item list-group-item-action">Documento Evaluar</a>
                </div>
              </div>
              <div class="col-8">
                <h5 class="estado fontI colorestados text-end">Estado Revisión: {{proyecto.investado}}</h5>
              </div>
            </div> 
          </div>
          <br>
          <!-- Espacio de comentarios -->
          <br />
          <!-- Botón para ver documento -->
          <h5 class="text fontI colortitle text-center">Comentarios Retroalimentativos</h5>
          {% for invcomentario in proyecto.comentarioinvcientifica_set.all %}
          <h6 class="text-end fontI  colorestados fechas ">
            {{ invcomentario.invfecha_post }} Por:  <span class="colortext fontI fecha">{{ invcomentario.user.nombre }} {{ invcomentario.user.apellido }}</span>
          </h6>
          <p class="comentario fontI colortext">Comentario:<br>{{ invcomentario.invcomentario }}</p>
          {% empty %}
          <p class="comentario fontI colortext">No hay comentarios para este proyecto.</p>
          {% endfor %}
        </div>
        <br>
      </div>
    </div>
  </div>
  <br>
  {% endfor %}
</div>

{% if proyectos.has_other_pages %}
<div class="pagination-container">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if proyectos.has_previous %}
      <li class="page-item">
        <a class="page-link dark-link" href="?page=1">&laquo; Primero</a>
      </li>
      <li class="page-item">
        <a class="page-link dark-link" href="?page={{ proyectos.previous_page_number }}">Anterior</a>
      </li>
      {% endif %}
  
      <li class="page-item disabled">
        <a class="page-link dark-link">Página {{ proyectos.number }} de {{ proyectos.paginator.num_pages }}</a>
      </li>
  
      {% if proyectos.has_next %}
      <li class="page-item">
        <a class="page-link dark-link" href="?page={{ proyectos.next_page_number }}">Siguiente</a>
      </li>
      <li class="page-item">
        <a class="page-link dark-link" href="?page={{ proyectos.paginator.num_pages }}">Último &raquo;</a>
      </li>
      {% endif %}
    </ul>
  </nav>
</div>
{% endif %}
{% else %}
<p class="fecha fontI colorfechas pt-3">No hay proyectos asociados a este usuario. Consulta en la administración.</p>
{% endif %}
{% endblock %}